repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.4"
    hooks:
      - id: ruff
        args: [ --config=pyproject.toml ]
      - id: ruff-format
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.0"
    hooks:
      - id: mypy
        args: [ --config=pyproject.toml ]
